### ISSUE TITLE
RegisterRequiredTypes(IContainerRegistry containerRegistry) double registers 

### ISSUE THREAD

**Issue by stevensrf11** [PrismLibrary/Prism-Samples-Forms#107] opened 2020-08-31 22:40 UTC
Is there a reason that each item registered in the RegisterRequiredTypes  static method  gets registered twice.
A item gets register with a name that null, then gets registered again with a name that is equal to  Pris,.xxx
For example the DialogService shown up registed in the container as 👍 

  | Name | Value | Type
-- | -- | -- | --
![1Untitled](https://user-images.githubusercontent.com/22349374/91775498-ccbe0c80-ebb0-11ea-8210-bb881dd46aba.png)

◢ | [8] | RegisteredType="IDialogService",    Name=null,    MappedTo="DialogService",    "ContainerControlledLifetimeManager" | Unity.IContainerRegistration {Unity.UnityContainer.ContainerRegistrationStruct}
  | ▶ LifetimeManager | {Lifetime:PerContainer} | Unity.Lifetime.LifetimeManager {Unity.Lifetime.ContainerControlledLifetimeManager}
  | ▶ MappedToType | {Name = "DialogService" FullName = "Prism.Services.Dialogs.DialogService"} | System.Type {System.RuntimeType}
  | Name | null | string
  | ▶ RegisteredType | {Name = "IDialogService" FullName = "Prism.Services.Dialogs.IDialogService"} | System.Type {System.RuntimeType}
◢ | [9] | RegisteredType="IDialogService",    Name="Prism.Services.Dialogs.DialogService, Prism.Wpf, Version=8.0.0.0, Culture=neutral, PublicKeyToken=40ee6c3a2184dc59",    MappedTo="DialogService",    "ContainerControlledLifetimeManager" | Unity.IContainerRegistration {Unity.UnityContainer.ContainerRegistrationStruct}
  | ▶ LifetimeManager | {Lifetime:PerContainer} | Unity.Lifetime.LifetimeManager {Unity.Lifetime.ContainerControlledLifetimeManager}
  | ▶ MappedToType | {Name = "DialogService" FullName = "Prism.Services.Dialogs.DialogService"} | System.Type {System.RuntimeType}
  | Name | "Prism.Services.Dialogs.DialogService, Prism.Wpf, Version=8.0.0.0, Culture=neutral, PublicKeyToken=40ee6c3a2184dc59" | string
  | ▶ RegisteredType | {Name = "IDialogService" FullName = "Prism.Services.Dialogs.IDialogService"} | System.Type {System.RuntimeType}

The attached images shows the items being double registered
  internal static void RegisterRequiredTypes(this IContainerRegistry containerRegistry, IModuleCatalog moduleCatalog)
        {
            containerRegistry.RegisterInstance(moduleCatalog);
            containerRegistry.RegisterSingleton<ILoggerFacade, TextLogger>();
            containerRegistry.RegisterSingleton<IDialogService, DialogService>();
            containerRegistry.RegisterSingleton<IModuleInitializer, ModuleInitializer>();
            containerRegistry.RegisterSingleton<IModuleManager, ModuleManager>();
            containerRegistry.RegisterSingleton<RegionAdapterMappings>();
            containerRegistry.RegisterSingleton<IRegionManager, RegionManager>();
            containerRegistry.RegisterSingleton<IRegionNavigationContentLoader, RegionNavigationContentLoader>();
            containerRegistry.RegisterSingleton<IEventAggregator, EventAggregator>();
            containerRegistry.RegisterSingleton<IRegionViewRegistry, RegionViewRegistry>();
            containerRegistry.RegisterSingleton<IRegionBehaviorFactory, RegionBehaviorFactory>();
            containerRegistry.Register<IRegionNavigationJournalEntry, RegionNavigationJournalEntry>();
            containerRegistry.Register<IRegionNavigationJournal, RegionNavigationJournal>();
            containerRegistry.Register<IRegionNavigationService, RegionNavigationService>();
            containerRegistry.Register<IDialogWindow, DialogWindow>(); //default dialog host
        }
![1Untitled](https://user-images.githubusercontent.com/22349374/91775513-d9426500-ebb0-11ea-9b7b-74ceed7685a6.png)

**Comment by dansiegel** [comment] 2020-08-31 22:51
Closing as this is not an issue for the Samples. @stevensrf11 feel free to ping me on the Sponsor Discord for clarification on this issue

**Closed by dansiegel** 2020-08-31 22:51 UTC

**Comment by brianlagunas** [comment] 2020-08-31 22:54
This is actually a great question. Something I was not aware of

**Comment by brianlagunas** [comment] 2020-08-31 23:10
Thanks for reporting. The duplication of registrations will be fixed. Apparently this was required to get Unity to properly support ResolveMany. However, if this is what it takes, then Unity will not support that feature.

**Comment by stevensrf11** [comment] 2020-09-01 00:04
It seems also if I register my own items they also get registered twice.

**Comment by dansiegel** [comment] 2020-09-01 01:27
this is by design. as I said if you ping me on the Sponsor Discord I'm happy to discuss it more with you there
